import NewsCard from "@/components/NewsCard";
import { Filter, SortDesc } from "lucide-react";
import { Button } from "@/components/ui/button";

const StockScreener = () => {
  const newsData = [
    {
      title: "Tesla Reports Strong Q4 Delivery Numbers Despite Market Concerns",
      summary: "Tesla delivered 484,507 vehicles in Q4, beating analyst expectations of 473,000 units. The strong performance comes amid concerns about EV market saturation and increased competition.",
      time: "2 hours ago",
      aiPrediction: "bullish" as const,
      confidence: 78
    },
    {
      title: "NVIDIA Faces New Export Restrictions on Advanced AI Chips",
      summary: "The Biden administration announced additional export controls on NVIDIA's most advanced AI chips to China, potentially impacting future revenue streams from the region.",
      time: "4 hours ago",
      aiPrediction: "bearish" as const,
      confidence: 82
    },
    {
      title: "Apple's Services Revenue Hits New All-Time High in Latest Quarter",
      summary: "Apple's services division generated record revenue of $23.1 billion, driven by App Store sales and subscription services, offsetting slower iPhone sales growth.",
      time: "6 hours ago",
      aiPrediction: "bullish" as const,
      confidence: 71
    },
    {
      title: "Meta Announces Major Layoffs Across Reality Labs Division",
      summary: "Meta plans to reduce its Reality Labs workforce by 20%, citing the need to streamline operations and focus on core metaverse initiatives with clearer ROI.",
      time: "8 hours ago",
      aiPrediction: "bearish" as const,
      confidence: 65
    },
    {
      title: "Microsoft Azure Revenue Accelerates with AI Services Integration",
      summary: "Microsoft's cloud computing platform Azure saw 30% revenue growth, largely attributed to new AI-powered services and enterprise adoption of GPT-integrated tools.",
      time: "12 hours ago",
      aiPrediction: "bullish" as const,
      confidence: 85
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8">
        <div className="space-y-8">
          {/* Header */}
          <div className="space-y-4 animate-fade-in">
            <div>
              <h1 className="text-4xl font-bold">Stock Screener</h1>
              <p className="text-lg text-muted-foreground">
                AI-powered market analysis and sentiment predictions
              </p>
            </div>

            {/* Filters */}
            {/* <div className="flex items-center space-x-2">
              <Button variant="outline" size="sm">
                <Filter className="h-4 w-4 mr-2" />
                Filter
              </Button>
              <Button variant="outline" size="sm">
                <SortDesc className="h-4 w-4 mr-2" />
                Sort by Time
              </Button>
            </div> */}
          </div>

          {/* Stats */}
          <div className="grid md:grid-cols-4 gap-6 animate-slide-up">
            <div className="bg-card border border-card-border rounded-lg p-4">
              <div className="text-sm text-muted-foreground">Market Sentiment</div>
              <div className="text-2xl font-bold text-success">Bullish</div>
            </div>
            <div className="bg-card border border-card-border rounded-lg p-4">
              <div className="text-sm text-muted-foreground">AI Predictions</div>
              <div className="text-2xl font-bold">1,247</div>
            </div>
            <div className="bg-card border border-card-border rounded-lg p-4">
              <div className="text-sm text-muted-foreground">Avg Confidence</div>
              <div className="text-2xl font-bold">76.2%</div>
            </div>
            <div className="bg-card border border-card-border rounded-lg p-4">
              <div className="text-sm text-muted-foreground">Success Rate</div>
              <div className="text-2xl font-bold">84.7%</div>
            </div>
          </div>

          {/* News Cards */}
          <div className="space-y-4">
            <h2 className="text-2xl font-semibold">Latest Market News & Analysis</h2>
            <div className="grid lg:grid-cols-2 gap-6">
              {newsData.map((news, index) => (
                <div key={index} className="animate-fade-in" style={{ animationDelay: `${index * 0.1}s` }}>
                  <NewsCard {...news} />
                </div>
              ))}
            </div>
          </div>

          {/* AI Disclaimer */}
          <div className="bg-muted/30 border border-card-border rounded-lg p-6 mt-8">
            <h3 className="font-semibold mb-2">AI Prediction Disclaimer</h3>
            <p className="text-sm text-muted-foreground">
              Predictions are generated by machine learning models analyzing market sentiment, news, and technical indicators. 
              Past performance does not guarantee future results. Always conduct your own research before making investment decisions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StockScreener;